BASE.WEB/Controllers/CustomersController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using BASE.ENTITIES.Custom;
using BASE.ENTITIES.Domain;
using BASE.SERVICES;
using BASE.UTILS;

namespace BASE.WEB.Controllers
{
    public class CustomersController : Controller
    {

        private readonly ICustomerService _customerService = DependecyFactory.GetInstance<ICustomerService>();

        // GET: Customers
        public ActionResult Index()
        {
            //IEnumerable<Customer> model = _customerService.GetAll();
            //return View(model);
            return View();
        }

        // GET: Customers/GetPage
        [HttpPost]
        public JsonResult GetPage()
        {
            int _start = Convert.ToInt32(Request.Form["start"]);
            int _length = Convert.ToInt32(Request.Form["length"]);
            int _draw = Convert.ToInt32(Request.Form["draw"]);
            int _idOrderColummn = Convert.ToInt32(Request.Form["order[0][column]"]);

            string _orderColumn = null;
            string _orderDirection = null;
            string _search = null;

            if (!String.IsNullOrEmpty(Request.Form["search[value]"]))
                _search = Request.Form["search[value]"];

            if (!String.IsNullOrEmpty(Request.Form["columns["+ _idOrderColummn +"][data]"]))
                _orderColumn = Request.Form["columns[" + _idOrderColummn + "][data]"];

            if (!String.IsNullOrEmpty(Request.Form["order[0][dir]"]))
                _orderDirection = Request.Form["order[0][dir]"];

            int _total = _customerService.GetTotal();
            int _totalFiltro = _customerService.GetTotalFiltro(_search);

            IEnumerable<Customer> model = _customerService.GetAllPaging(_start, _length, _search, _orderColumn, _orderDirection);

            return Json(new
            {
                search = _search,
                draw = _draw,
                recordsTotal = _total,
                recordsFiltered = _totalFiltro,
                data = model,

            });
        }

        // GET: Customers/Details/5
        public ActionResult Details(int id)
        {
            var model = _customerService.Get(id);
            return View(model);
        }

        // GET: Customers/Create
        public ActionResult Create()
        {
            return View();
        }

        // POST: Customers/Create
        [HttpPost]
        public ActionResult Create(Customer customer)
        {

            if (ModelState.IsValid)
            {
                _customerService.InsertOrUpdate(customer);
                return RedirectToAction("Index");
            }

            return View();

        }

        // GET: Customers/Edit/5
        public ActionResult Edit(int id)
        {
            var model = _customerService.Get(id);
            return View(model);
        }

        // POST: Customers/Edit/5
        [HttpPost]
        public ActionResult Edit(Customer customer)
        {

            if (ModelState.IsValid)
            {
                var rh = _customerService.InsertOrUpdate(customer);
                if (rh.Response)
                {
                    return RedirectToAction("index");
                }
            }

            return View(customer);
        }

        // POST: Customers/Delete/5
        [HttpPost]
        public JsonResult Delete(int id)
        {
            int response = 0;

            response = _customerService.Delete(id);

            if (response > 0)
                return Json(new {value = 1, message = "Record deleted!"});
            else
                return Json(new {value = 0, message = "Can't delete record!"});

        }
    }
}

BASE.WEB/Controllers/HomeController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace BASE.WEB.Controllers
{
    public class HomeController : Controller
    {
        public ActionResult Index()
        {
            return View();
        }
        
    }
}

BASE.WEB/Views/Customers/Create.cshtml
@model BASE.ENTITIES.Domain.Customer

@{
    ViewBag.Title = "Create";
}

<div class="box">
    
    @using (Html.BeginForm())
    {
        <div class="box-header with-border">
            <h3 class="box-title">Create</h3>
        </div>
        <div class="box-body">
            <div class="row col-xs-12 col-sm-6">

                @Html.AntiForgeryToken()

                <div class="form-horizontal">

                    @Html.ValidationSummary(true, "", new {@class = "text-danger"})

                    <div class="form-group">
                        @Html.LabelFor(model => model.FirstName, htmlAttributes: new {@class = "control-label col-md-2"})
                        <div class="col-md-10">
                            @Html.EditorFor(model => model.FirstName, new {htmlAttributes = new {@class = "form-control", placeholder = "First name" } })
                            @Html.ValidationMessageFor(model => model.FirstName, "", new {@class = "text-danger"})
                        </div>
                    </div>

                    <div class="form-group">
                        @Html.LabelFor(model => model.LastName, htmlAttributes: new {@class = "control-label col-md-2"})
                        <div class="col-md-10">
                            @Html.EditorFor(model => model.LastName, new {htmlAttributes = new {@class = "form-control", placeholder = "Last name" } })
                            @Html.ValidationMessageFor(model => model.LastName, "", new {@class = "text-danger"})
                        </div>
                    </div>
                </div>
            </div>
        </div>

        <div class="box-footer">
            <div class="row col-xs-12 col-sm-6">
                @Html.ActionLink("Back to List", "Index", null, new {@class = "btn btn-default"})

                <button type="submit" class="btn btn-info pull-right"><i class="fa fa-floppy-o"></i> Create</button>
            </div>
        </div>
    }
</div>

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

BASE.WEB/Views/Customers/Details.cshtml
@model BASE.ENTITIES.Domain.Customer

@{
    ViewBag.Title = "Details";
}

<div class="box">
    <div class="box-header with-border">
        <h3 class="box-title">Details</h3>
    </div>
    <div class="box-body">
        <div class="row col-xs-12 col-sm-6">
            <div class="form-horizontal">

                <div class="form-group">
                    @Html.LabelFor(model => model.FirstName, htmlAttributes: new { @class = "control-label col-md-2" })
                    <div class="col-md-10">
                        <label class="control-text">
                            @Html.DisplayFor(model => model.FirstName)
                        </label>
                    </div>
                </div>

                <div class="form-group">
                    @Html.LabelFor(model => model.LastName, htmlAttributes: new { @class = "control-label col-md-2" })
                    <div class="col-md-10">
                        <label class="control-text">
                            @Html.DisplayFor(model => model.LastName)
                        </label>

                    </div>
                </div>

                <div class="form-group">
                    @Html.LabelFor(model => model.CreatedAt, htmlAttributes: new { @class = "control-label col-md-2" })
                    <div class="col-md-10">
                        <label class="control-text">
                            @Html.DisplayFor(model => model.CreatedAt)
                        </label>

                    </div>
                </div>

                <div class="form-group">
                    @Html.LabelFor(model => model.CreatedBy, htmlAttributes: new { @class = "control-label col-md-2" })
                    <div class="col-md-10">
                        <label class="control-text">
                            @Html.DisplayFor(model => model.CreatedBy)
                        </label>

                    </div>
                </div>

                <div class="form-group">
                    @Html.LabelFor(model => model.UpdatedAt, htmlAttributes: new { @class = "control-label col-md-2" })
                    <div class="col-md-10">
                        <label class="control-text">
                            @Html.DisplayFor(model => model.UpdatedAt)
                        </label>

                    </div>
                </div>

                <div class="form-group">
                    @Html.LabelFor(model => model.UpdatedBy, htmlAttributes: new { @class = "control-label col-md-2" })
                    <div class="col-md-10">
                        <label class="control-text">
                            @Html.DisplayFor(model => model.UpdatedBy)
                        </label>

                    </div>
                </div>

                <div class="form-group">
                    @Html.LabelFor(model => model.DeletedAt, htmlAttributes: new { @class = "control-label col-md-2" })
                    <div class="col-md-10">
                        <label class="control-text">
                            @Html.DisplayFor(model => model.DeletedAt)
                        </label>

                    </div>
                </div>

                <div class="form-group">
                    @Html.LabelFor(model => model.DeletedBy, htmlAttributes: new { @class = "control-label col-md-2" })
                    <div class="col-md-10">
                        <label class="control-text">
                            @Html.DisplayFor(model => model.DeletedBy)
                        </label>

                    </div>
                </div>

            </div>
        </div>
    </div>
    <div class="box-footer">
        <div class="row col-xs-12 col-sm-6">
            @Html.ActionLink("Back to List", "Index", null, new {@class= "btn btn-default" })
            <a href="@Url.Action("Edit", "Customers", new { id = Model.Id })" class="btn btn-info"><i class="fa fa-pencil"></i> Edit </a>
        </div>
    </div>
</div>

BASE.WEB/Views/Customers/Edit.cshtml
@model BASE.ENTITIES.Domain.Customer

@{
    ViewBag.Title = "Edit";
}

<div class="box">
    @using (Html.BeginForm())
    {
        <div class="box-header with-border">
            <h3 class="box-title">Edit</h3>
        </div>

        <div class="box-body">
            <div class="row col-xs-12 col-sm-6">

                @Html.AntiForgeryToken()

                <div class="form-horizontal">
              
                    @Html.ValidationSummary(true, "", new { @class = "text-danger" })

                    @Html.HiddenFor(model => model.Id)

                    <div class="form-group">
                        @Html.LabelFor(model => model.FirstName, htmlAttributes: new { @class = "control-label col-md-2" })
                        <div class="col-md-10">
                            @Html.EditorFor(model => model.FirstName, new { htmlAttributes = new { @class = "form-control" } })
                            @Html.ValidationMessageFor(model => model.FirstName, "", new { @class = "text-danger" })
                        </div>
                    </div>

                    <div class="form-group">
                        @Html.LabelFor(model => model.LastName, htmlAttributes: new {@class = "control-label col-md-2"})
                        <div class="col-md-10">
                            @Html.EditorFor(model => model.LastName, new {htmlAttributes = new {@class = "form-control"}})
                            @Html.ValidationMessageFor(model => model.LastName, "", new {@class = "text-danger"})
                        </div>
                    </div>

                </div>
            </div>
        </div>

        <div class="box-footer">
            <div class="row col-xs-12 col-sm-6">
                @Html.ActionLink("Back to List", "Index", null, new { @class = "btn btn-default" })
                <button type="submit" class="btn btn-info pull-right"><i class="fa fa-floppy-o"></i> Save</button>
            </div>
        </div>

    }
    </div>

    @section Scripts {
        @Scripts.Render("~/bundles/jqueryval")
    }

BASE.WEB/Views/Customers/Index.cshtml
@model IEnumerable<BASE.ENTITIES.Domain.Customer>

@{
    ViewBag.Title = "Index";
}

@section AddCSS{
    <link href="@Url.Content("~/Scripts/plugins/datatables/dataTables.bootstrap.css")" rel="stylesheet" type="text/css" />
}

<div class="box">
    
    <p>@ViewBag.star</p>
    <p>@ViewBag.length</p>

    <div class="box-header with-border">
        <h3 class="box-title">
            List
        </h3>
        @Html.ActionLink("Create New", "Create", null, new {@class = "btn btn-default pull-right"})
    </div>

    <div class="box-body">

        <table id="dataTable" class="table table-bordered table-hover">
            <thead>
            <tr>
                <th>
                    @Html.DisplayNameFor(model => model.FirstName)
                </th>
                <th>
                    @Html.DisplayNameFor(model => model.LastName)
                </th>
                <th>
                    @Html.DisplayNameFor(model => model.CreatedAt)
                </th>
                <th>
                    @Html.DisplayNameFor(model => model.CreatedBy)
                </th>
                <th>
                    @Html.DisplayNameFor(model => model.UpdatedAt)
                </th>
                <th>
                    @Html.DisplayNameFor(model => model.UpdatedBy)
                </th>
                <th>
                    @Html.DisplayNameFor(model => model.DeletedAt)
                </th>
                <th>
                    @Html.DisplayNameFor(model => model.DeletedBy)
                </th>
                <th>Actions</th>
            </tr>
            </thead>

            <tbody></tbody>

            <tfoot>
            <tr>
                <th>
                    @Html.DisplayNameFor(model => model.FirstName)
                </th>
                <th>
                    @Html.DisplayNameFor(model => model.LastName)
                </th>
                <th>
                    @Html.DisplayNameFor(model => model.CreatedAt)
                </th>
                <th>
                    @Html.DisplayNameFor(model => model.CreatedBy)
                </th>
                <th>
                    @Html.DisplayNameFor(model => model.UpdatedAt)
                </th>
                <th>
                    @Html.DisplayNameFor(model => model.UpdatedBy)
                </th>
                <th>
                    @Html.DisplayNameFor(model => model.DeletedAt)
                </th>
                <th>
                    @Html.DisplayNameFor(model => model.DeletedBy)
                </th>
                <th>Actions</th>
            </tr>
            </tfoot>
        </table>
    </div>

</div>

@section scripts{
    <script src="@Url.Content("~/Scripts/plugins/datatables/jquery.dataTables.min.js")"></script>
    <script src="@Url.Content("~/Scripts/plugins/datatables/dataTables.bootstrap.min.js")"></script>
    <script src="@Url.Content("~/Scripts/plugins/moment/moment.min.js")"></script>

    <script>

        var _detail = '<a href="@Url.Action("Details", "Customers", new {id = "params"})" class="btnActionRow" title="view details"><i class="fa fa-plus-square-o"></i></a>';
        var _edit   = '<a href="@Url.Action("Edit", "Customers", new {id = "params"})" class="btnActionRow" title="edit"><i class="fa fa-pencil"></i></a>';
        var _delete = '<a href="@Url.Action("Delete", "Customers", new {id = "params"})" class="btnActionRow btnDeleteRow" title="delete"><i class="fa fa-trash-o"></i></a>';
        
        var table = $('#dataTable')
            .DataTable({
                "responsive": true,
                "processing": true,
                "serverSide": true,
                "ajax": {
                    "url": "Customers/GetPage",
                    "type": "POST",
                    "dataType": "json",
                    "dataSrc": "data"
                },
                "columns": [
                    { data: "FirstName" },
                    { data: "LastName" },
                    {
                        data: "CreatedAt",
                        "type": "date",
                        "render":
                            function(data, type, full) {
                                return (data) ? moment(data).format('DD/MM/YYYY') : '';
                            }
                    },
                    { data: "CreatedBy" },
                    {
                        data: "UpdatedAt",
                        "type": "date",
                        "render":
                            function(data, type, full) {
                                return (data) ? moment(data).format('DD/MM/YYYY') : '';
                            }
                    },
                    { data: "UpdatedBy" },
                    { data: "DeletedAt" },
                    { data: "DeletedBy" },
                    {
                        data: "Id",
                        "type": "numeric",
                        "render": function(data, type, full, meta) {

                            var butonDetail = _detail.replace("params", data);
                            var buttonEdit = _edit.replace("params", data);
                            var buttonDelete = _delete.replace("params", data);

                            return butonDetail + buttonEdit + buttonDelete;
                        },
                        "createdCell": function(td, cellData, rowData, row, col) {
                            $(td).addClass('text-center');
                        }
                    }
                ],
                "drawCallback": function() {
                    btnDeleteRow();
                },
                "initComplete": function () {
                    $("#dataTable").wrap("<div class='table-responsive'></div>");                    $("#dataTable").css("width", "100%");
                }

            });

        function btnDeleteRow() {
            $('.btnDeleteRow')
                .click(function(e) {

                    e.preventDefault();
                    var _this = $(this);
                    var url = _this.prop('href');

                    alertify.confirm('Base CMS',
                        'Are you sure to delete the record?',
                        function() {
                            $.post(url,
                                    function(data) {
                                        if (data.value == 1) {

                                            _this.closest('tr').find('a').css('color', '#fff');

                                            _this.closest('tr')
                                                .children()
                                                .css('background', '#ed2f5e')
                                                .css('color', '#fff')
                                                .delay(300)
                                                .slideUp(300)
                                                .queue(function() {
                                                    _this.closest('tr').remove().dequeue();
                                                    table.ajax.reload(null, false);
                                                });
                                        } else {
                                            alertify.alert('Error', data.mensaje);
                                        }
                                    },
                                    "json")
                                .fail(function () {
                                    alertify.alert('Error', 'An error occurred while attempting to delete the record');
                                });
                        },
                        function () {

                        });
                });
        }

    </script>
}

BASE.WEB/Views/Home/Index.cshtml
@{
    ViewBag.Title = "BaseCMS";
}

BASE.WEB/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">

    <title>@ViewBag.Title - BASE</title>
    @Styles.Render("~/Content/css")
    @Scripts.Render("~/bundles/modernizr")

    @RenderSection("AddCSS", required: false)

    <!-- Tell the browser to be responsive to screen width -->
    <meta content="width=device-width, initial-scale=1, maximum-scale=1, user-scalable=no" name="viewport">
    <!-- Bootstrap 3.3.6 -->
    @*<link rel="stylesheet" href="../../bootstrap/css/bootstrap.min.css">*@
    <!-- Font Awesome -->
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css">
    <!-- Ionicons -->
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/ionicons/2.0.1/css/ionicons.min.css">
    <!-- Theme style -->
    @*<link rel="stylesheet" href="Content/AdminLTE.min.css">*@
    <!-- AdminLTE Skins. Choose a skin from the css/skins
         folder instead of downloading all of them to reduce the load. -->
    @*<link rel="stylesheet" href="Content/_all-skins.min.css">*@
    <!-- HTML5 Shim and Respond.js IE8 support of HTML5 elements and media queries -->
    <!-- WARNING: Respond.js doesn't work if you view the page via file:// -->
    <!--[if lt IE 9]>
    <script src="https://oss.maxcdn.com/html5shiv/3.7.3/html5shiv.min.js"></script>
    <script src="https://oss.maxcdn.com/respond/1.4.2/respond.min.js"></script>
    <![endif]-->
</head>
<body class="hold-transition skin-blue sidebar-mini">
    <!-- Site wrapper -->
    <div class="wrapper">
        <header class="main-header">
            <!-- Logo -->
            <a href="@Url.Action("Index","Home")" class="logo">
                <!-- mini logo for sidebar mini 50x50 pixels -->
                <span class="logo-mini"><b>B</b>SE</span>
                <!-- logo for regular state and mobile devices -->
                <span class="logo-lg"><b>Base</b>CMS</span>
            </a>
            <!-- Header Navbar: style can be found in header.less -->
            <nav class="navbar navbar-static-top">
                <!-- Sidebar toggle button-->
                <a href="#" class="sidebar-toggle" data-toggle="offcanvas" role="button">
                    <span class="sr-only">Toggle navigation</span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </a>
                <div class="navbar-custom-menu">
                    <ul class="nav navbar-nav">
                        <li class="dropdown user user-menu">
                            <a href="#" class="dropdown-toggle" data-toggle="dropdown">
                                <i class="fa fa-user-o"></i>
                                <span class="hidden-xs">Omar Diaz</span>
                            </a>
                            <ul class="dropdown-menu">
                                <!-- User image -->
                                <li class="user-header">
                                    <i class="fa fa-user-circle-o fa-4x"></i>
                                    <p>
                                        Omar Diaz - Web Developer
                                        <small>Member since Nov. 2010</small>
                                    </p>
                                </li>
                                <!-- Menu Body -->
                                <li class="user-body">
                                    <div class="row">
                                        <div class="col-xs-4 text-center">
                                            <a href="#">Followers</a>
                                        </div>
                                        <div class="col-xs-4 text-center">
                                            <a href="#">Sales</a>
                                        </div>
                                        <div class="col-xs-4 text-center">
                                            <a href="#">Friends</a>
                                        </div>
                                    </div>
                                    <!-- /.row -->
                                </li>
                                <!-- Menu Footer-->
                                <li class="user-footer">
                                    <div class="pull-left">
                                        <a href="#" class="btn btn-default btn-flat">Profile</a>
                                    </div>
                                    <div class="pull-right">
                                        <a href="#" class="btn btn-default btn-flat">Sign out</a>
                                    </div>
                                </li>
                            </ul>
                        </li>
                        <!-- Control Sidebar Toggle Button -->
                        <li>
                            <a href="#" data-toggle="control-sidebar" title="sign out"><i class="fa fa-sign-out"></i> Sign out</a>
                        </li>
                    </ul>
                </div>
            </nav>
        </header>
        <!-- =============================================== -->
        <!-- Left side column. contains the sidebar -->
        <aside class="main-sidebar">
            <!-- sidebar: style can be found in sidebar.less -->
            <section class="sidebar">
                <!-- Sidebar user panel -->
                <div class="user-panel">
                    <div class="pull-left image">
                        <i class="fa fa-user-circle-o size-ico-user"></i>
                    </div>
                    <div class="pull-left info">
                        <p>Omar Diaz</p>
                        <a href="#"><i class="fa fa-circle text-success"></i> Online</a>
                    </div>
                </div>
                <!-- search form -->
                <form action="#" method="get" class="sidebar-form">
                    <div class="input-group">
                        <input type="text" name="q" class="form-control" placeholder="Search...">
                        <span class="input-group-btn">
                            <button type="submit" name="search" id="search-btn" class="btn btn-flat">
                                <i class="fa fa-search"></i>
                            </button>
                        </span>
                    </div>
                </form>
                <!-- /.search form -->
                <!-- sidebar menu: : style can be found in sidebar.less -->
                <ul class="sidebar-menu">
                    <li class="header">MAIN NAVIGATION</li>
                    @{
                        string strUrl = Request.Url.AbsoluteUri.ToString();
                        string strController = @HttpContext.Current.Request.RequestContext.RouteData.Values["controller"].ToString();
                    }
                    <li class="@(strUrl.Contains(strController)?"active":"")">
                        <a href="@Url.Action("Index","Customers")">
                            <i class="fa fa-table"></i>
                            <span>Customers</span>
                        </a>
                    </li>

                </ul>
            </section>
            <!-- /.sidebar -->
        </aside>
        <!-- =============================================== -->
        <!-- Content Wrapper. Contains page content -->
        <div class="content-wrapper">
            <!-- Content Header (Page header) -->
            <section class="content-header">
                <h1>
                    @ViewBag.Title
                    <small>@ViewBag.SubTitle</small>
                </h1>
                <ol class="breadcrumb">
                    <li><a href="#"><i class="fa fa-dashboard"></i> Home</a></li>
                    <li><a href="#">@strController</a></li>
                    <li class="active">@ViewBag.Title</li>
                </ol>
            </section>
            <!-- Main content -->
            <section class="content">
                <div class="row">
                    <div class="col-xs-12">
                        @RenderBody()
                    </div>
                </div>
            </section>
            <!-- /.content -->
        </div>
        <!-- /.content-wrapper -->
        <footer class="main-footer">
            <div class="pull-right hidden-xs">
                <b>Version</b> 1.1
            </div>
            <strong>Copyright &copy; 2017 <a href="http://twitter.com/omardiaze" target="_blank">omardiaze</a>.</strong> All rights reserved.
        </footer>
    </div>
<!-- ./wrapper -->

    

    <!-- AdminLTE App -->
    @*<script src="Scripts/app.min.js"></script>*@
    <!-- AdminLTE for demo purposes -->
    @*<script src="Scripts/demo.js"></script>*@

    @Scripts.Render("~/bundles/jquery")

    @Scripts.Render("~/bundles/bootstrap")

    @Scripts.Render("~/bundles/plugins")

    @Scripts.Render("~/bundles/app")

    @RenderSection("scripts", required: false)

</body>
</html>